# "BLEU" "Model" "Merge"
path: verl/utils/reward_score/mt_score.py
name: compute_score
reward_kwargs:
  scale_factor: 100.0
  # if not use, format_reward will not be used 
  reward_metric: Merge
  mul_times: 2